version: '3.0'
services:
  web:
    container_name: php_teste
    build: .
    ports:
      - '1234:80'
    volumes:
      - ./app:/var/www/html
    links:
      - mariadb
  mariadb:
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes:
      - database:/var/lib/mysql
      - ./DDL/schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci


volumes:
  database:
